### ISSUE TITLE
Test suite not working correctly

### ISSUE THREAD

**Issue by Joon** [LK-MUG/BuildYourFirstWebPart#1]
If I run "jest", I get an error "begin is not defined"

Assuming that Jest's typescript compiler is not getting references correctly. I've tried various things but can't get it working.

@VelinGeorgiev can you please check what is wrong with the project setup?

Thanks!

**Comment by VelinGeorgiev** [comment]
@Joon , will have a look ASAP

**Comment by Joon** [comment]
Thanks Velin!

**Comment by VelinGeorgiev** [comment]
@Joon  I think I was able to resolve your issue. Commit https://github.com/LK-MUG/BuildYourFirstWebPart/commit/b4f5f1a4712621fa2116ea99ea9f1db0ccd45c66

Let me know if any questions.

**Comment by Joon** [comment]
Tested and working fine now. Thanks again!
